flake: remove numtide/flake-utils
gabm/Satty pull request #102
Opened 2024-07-14 20:55 UTC by jacekpoz

this flake's usage of flake-utils is trivial enough where we can replace it with a few lines of boilerplate

this gives us the benefit of having one less input and removing a lot of hidden complexity and potentially another copy of flake-utils from the devs' computers

this is also a great post on the matter: https://ayats.org/blog/no-flake-utils

2024-07-14 20:56 UTC, NotAShelf commented
+1 for removing flake-utils! It's a relic from a less civilized era

2024-07-14 21:28 UTC, diniamo requested changes
Other than that, +1, flake-utils bad >:(

2024-07-14 21:28 UTC, diniamo commented on flake.nix
> +          shellHook = with pkgs; ''
Don't use `with pkgs` here

2024-07-14 21:28 UTC, diniamo commented on flake.nix
> +        pkgs = import nixpkgs {inherit system overlays;};
Don't import `nixpkgs`, use `nixpkgs.legacyPackages.${system}` instead. `rust-overlay` also exposes its packages via `rust-overlay.packages.${system}`.

See https://zimbatm.com/notes/1000-instances-of-nixpkgs, if you want a detailed reasoning.

2024-07-14 21:28 UTC, gabm commented
thanks .. extra 👍 for the link!

2024-07-14 21:28 UTC, merged

2024-07-14 21:29 UTC, diniamo commented
...

2024-07-15 06:50 UTC, gabm commented
@diniamo i didn't see your review before merging - sorry!