option to specify the "corner roundness"
gabm/Satty pull request #140
Opened 2024-12-19 14:59 UTC by schaumtier

new option "corner-roundness". "0" means no corners. "12" is the default value (which draws corners of rectangle, blur and highlight round.

2024-12-19 15:21 UTC, LordMZTE requested changes
Thanks! I left some comments on things I believe could be improved.

2024-12-19 15:21 UTC, LordMZTE commented on README.md
> +corner_roundness = 12,
There shouldn't be a comma here. We should also consider writing `12.0` to clarify that this is a float, not an int.

2024-12-19 15:21 UTC, LordMZTE commented on src/style.rs
> +    pub fn to_corner_roundness(self) -> f32 {
Why is this function needed? It always returns the same value, regardless of `self`. At a glance, it also seems unused.

2024-12-19 15:21 UTC, LordMZTE commented on src/style.rs
> +pub struct Properties {}
Why do we need this struct?

2024-12-19 15:21 UTC, LordMZTE commented on src/style.rs
> +    pub fn corner_roundness() -> f32 {
This seems a little redundant. Perhaps we could directly reference `APP_CONFIG.read().corner_roundness()` where it's used.

2024-12-19 15:23 UTC, schaumtier commented on README.md
> +corner_roundness = 12,
removed it already

2024-12-19 15:25 UTC, schaumtier commented on src/style.rs
> +    pub fn to_corner_roundness(self) -> f32 {
that's right - I just forgot to remove it

2024-12-19 15:29 UTC, schaumtier commented on src/style.rs
> +pub struct Properties {}
i don't really know - just needed a place to attach the getter function... maybe its better kept somewhere else. rust is really not my programming language

2024-12-19 15:37 UTC, schaumtier commented on src/style.rs
> +    pub fn corner_roundness() -> f32 {
initially i thought of the need to differentiate between "Small", "Medium" and "Large" - thats why i've made a function. but of course would it be enough to have the numeric value.
if it's okay to reference APP_CONFIG directly in e.g. rectangle.rs, i can do this there.

2024-12-20 09:51 UTC, LordMZTE approved these changes

2024-12-20 10:44 UTC, merged

2024-12-20 10:44 UTC, gabm commented
great, thank you both!